# Generated by Django 5.0.4 on 2024-05-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_payment_course_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="sessions_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="id сессии"
            ),
        ),
    ]
