# Generated by Django 5.0.4 on 2024-05-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_options_payment_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="sessions_id",
            new_name="session_id",
        ),
    ]
