# Generated by Django 5.0.4 on 2024-04-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(max_length=100, verbose_name="описание"),
        ),
    ]
