# Generated by Django 5.0.4 on 2024-04-30 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_video_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="description",
            new_name="description_lesson",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="title",
            new_name="title_lesson",
        ),
    ]
