# Generated by Django 5.0.4 on 2024-04-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_rename_description_lesson_description_lesson_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="description_lesson",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="title_lesson",
            new_name="title",
        ),
    ]
