# Generated by Django 5.0.4 on 2024-04-30 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_rename_description_lesson_lesson_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="описание"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="materials/", verbose_name="превью"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.lesson",
                verbose_name="урок",
            ),
        ),
    ]
