# Generated by Django 5.0.4 on 2024-05-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_alter_lesson_description_alter_lesson_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="lesson",
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="урок",
            ),
        ),
    ]
