# Generated by Django 5.0.4 on 2024-05-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_remove_course_lesson_lesson_lesson"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="lesson",
            new_name="course",
        ),
    ]
